spring:
  datasource:
    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1'
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
api:
  endpoint:
    url: /api/v1